language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
cache:
  directories:
    - $HOME/.cache/pip
addons:
  postgresql: "9.4"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install coveralls flake8 tox

before_script:
  - python3 -m flake8 .
  - psql -c 'create database doko;' -U postgres
  - head -c 24 /dev/urandom > cookie_secret
  - echo 'debug=True' > local_config.py
  # other things...
  #- python3 webapp.py --cookie_secret=c --debug=True --https=False &

script:
  - tox -e cover

after_success: coveralls

notifications:
  email:
    on_failure: change
