language: python
python:
  - "3.3"

# prerequisite 
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-contrib
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3

# command to install dependencies
install:
  - pip install -r requirements.txt
  - yes | pip uninstall nose 
  - pip install nose==1.3.4 
  - pip install coverage

# database
before_script:
  - psql -c 'create database doko;' -U postgres
  - python3 manage_db.py
  - psql -U postgres -d doko -f tests/fixtures/all-encompassing.sql

# command to run tests
script: 
  - nosetests --with-coverage --cover-inclusive --cover-branches --cover-package=api,db,webapp

notifications:
  irc:
    channels: "irc.freenode.org#sel-columbia"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email:
    on_failure: change
