language: python
python:
  - "3.3"
  - "3.4"
addons:
  postgresql: "9.3"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-testing.txt
  - pip install -r requirements-graphing.txt
  - pip install coverage

# database
before_script:
  - psql -c 'create database doko;' -U postgres
  - python3 manage_db.py
  - psql -U postgres -d doko -f tests/fixtures/all-encompassing.sql
  - python3 webapp.py &

# command to run tests
script: 
  - nosetests --with-coverage --cover-inclusive --cover-branches --cover-tests --cover-html --cover-erase --cover-package=api,db,webapp,pages.api,pages.util,pages.debug,pages.view --ignore-files=selenium_test

notifications:
  irc:
    channels: "irc.freenode.org#sel-columbia"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email:
    on_failure: change
  hipchat:
    rooms:
      secure: O1kfcW59uDkeCOj4NcxHpwCL77pfFxiRosfoRaXedMcV9llJZkZ7IYCc4HLIr52/sTN2eBrFetOoywRL3nrcrfaKIdbW+Dc+IdmesmOI1xMomsY+yWM79q38D1jiwkHbsGQIH4GTSsLSwTf8lFt7KfM3nKAgwEjApq8+zvnSM1w=
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change

