language: python
python:
  - "3.3"

# prerequisite 
before_install:
  - sudo apt-get update
  - sudo apt-get install postgresql-contrib
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
  - /bin/bash run_tests.bash
