language: python
python:
  - "3.3"

# prerequisite 
before_install:
  - sudo apt-get update
  - sudo apt-get install postgresql-contrib
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start

# command to install dependencies
install:
  - pip install -r requirements.txt

# database
before_script:
  - psql -c 'create database doko;' -U postgres
  - python3 manage_db.py
  - psql -U postgres -d doko -f ebola-fixtures/insert_fixture.sql

# command to run tests
script: 
  - /bin/bash run_tests.bash

notifications:
  irc: "irc.freenode.org#sel-columbia"
