language: python
python:
  - "3.3"
  - "3.4"
cache:
  pip: true
  directories:
    - node_modules
sudo: false
addons:
  postgresql: "9.4"

# command to install dependencies
# or at least it would be...? moving this to before_script so that Travis will cache dependencies

# what would go in "install" plus
# database and flake8
before_script:
  - pip install -r requirements.txt
  - pip install -r requirements-testing.txt
  - pip install coveralls flake8
  - python3 -m flake8 .
  - psql -c 'create database doko;' -U postgres
  - python3 manage_db.py
  - psql -U postgres -d doko -f tests/fixtures/all-encompassing.sql
  - nvm install iojs
  - npm install --python=python2.7
  - echo 'APP_DEBUG=True' > dokomoforms/local_settings.py
  - python3 webapp.py &

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# command to run tests
script: 
  - npm test
  - nosetests -c .noserc

after_success: coveralls

notifications:
  irc:
    channels: "irc.freenode.org#sel-columbia"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email:
    on_failure: change
  hipchat:
    rooms:
      secure: O1kfcW59uDkeCOj4NcxHpwCL77pfFxiRosfoRaXedMcV9llJZkZ7IYCc4HLIr52/sTN2eBrFetOoywRL3nrcrfaKIdbW+Dc+IdmesmOI1xMomsY+yWM79q38D1jiwkHbsGQIH4GTSsLSwTf8lFt7KfM3nKAgwEjApq8+zvnSM1w=
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change

