language: python
python:
  - "3.3"
  - "3.4"
cache: pip
sudo: false
env:
  global:
    - secure: C/Ni0z3WjMsxFtHImuU7OqMlYg8fsON74Xwx/wlhvFHuKfiu8Y6o40/VXSUp7vqhjGJF3jmdWPmwlk2lNg0HwYbTaDBfB9Zr6yHlPKW4uqhWCibIBUN9K0p7Xv1Jp8j3TmSJc1uelLHOtYNYVW8bqyvt7qMqUqYGaGSiH1zU0nA=
    - secure: V0rdSDV1xC8gLK8KC0q9MTe/LHl/yvN51fglqJCY8Keq0FC1rcrIP+Z0nRY5ORxOC4Fv4DJp3uvNktnnW2bVdDDuKc8emEMR/on33Xjp5WcaioADk59YMl+kaMD3DGE1Hqn0/WFnMw8UyYCahBnJuDZMyGJVZyV4FPgGjiMsfU0=
addons:
  postgresql: "9.4"
  sauce_connect: true

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-testing.txt
  - pip install coverage coveralls
  - pip install flake8

# database and flake8
before_script:
  - python3 -m flake8 .
  - psql -c 'create database doko;' -U postgres
  - python3 manage_db.py
  - psql -U postgres -d doko -f tests/fixtures/all-encompassing.sql
  - npm install --python=python2.7
  - echo 'APP_DEBUG=True' > local_settings.py
  - python3 webapp.py &

# command to run tests
script: 
  - npm test
  - nosetests --with-coverage --cover-inclusive --cover-branches --cover-tests --cover-html --cover-erase --cover-package=api,db,webapp,pages.api,pages.util,pages.debug,pages.view

after_script: ps aux | grep '[b]in/sc'

after_success: coveralls

notifications:
  irc:
    channels: "irc.freenode.org#sel-columbia"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email:
    on_failure: change
  hipchat:
    rooms:
      secure: O1kfcW59uDkeCOj4NcxHpwCL77pfFxiRosfoRaXedMcV9llJZkZ7IYCc4HLIr52/sTN2eBrFetOoywRL3nrcrfaKIdbW+Dc+IdmesmOI1xMomsY+yWM79q38D1jiwkHbsGQIH4GTSsLSwTf8lFt7KfM3nKAgwEjApq8+zvnSM1w=
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change

