language: python
python:
  - "3.4"
  - "3.5"
cache:
  directories:
    - $HOME/.cache/pip
addons:
  postgresql: "9.4"
  firefox: "39.0"

install:
  - pip install coveralls flake8 tox

before_script:
  - python3 -m flake8 .
  - psql -c 'create database doko;' -U postgres
  - head -c 24 /dev/urandom > cookie_secret

script:
  - xvfb-run tox -e cover

after_success: coveralls

notifications:
  email:
    on_failure: change
