language: python
python:
  - "3.4"
  - "3.5"
cache:
  directories:
    - $HOME/.cache/pip
addons:
  postgresql: "9.4"
  firefox: "39.0"

before_install:
  - pip install coveralls flake8 coverage beautifulsoup4 py-dateutil selenium

before_script:
  - python3 -m flake8 .
  - psql -c 'create database doko;' -U postgres
  - head -c 24 /dev/urandom > cookie_secret
  - ./tests/selenium_webapp.py > /dev/null 2>&1 &
  - sleep 2

script:
  - xvfb-run tests/coverage_run.sh

after_success: coveralls

notifications:
  email:
    on_failure: change
