version: '2'
services:
  nginx:
    image: "nginx:1.9.9"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp:/tmp
    volumes_from:
      - webapp
  webapp:
    image: "selcolumbia/dokomoforms:0.2.10"
    command: bash -c "./docker-wait-for-postgres.sh db && head -c 24 /dev/urandom > cookie_secret && python webapp.py"
    volumes:
      - ./local_config.py:/dokomo/local_config.py
      - /var/www
    depends_on:
      - db
  db:
    image: "mdillon/postgis:9.4"
    environment:
      POSTGRES_DB: 'doko'
