webapp:
  image: "selcolumbia/dokomoforms"
  command: bash -c "head -c 24 /dev/urandom > cookie_secret && python webapp.py"
  links:
    - "db:db"
  ports:
    - "8888:8888"
db:
  image: "mdillon/postgis:9.4"
  environment:
    POSTGRES_PASSWORD: 'password'
    POSTGRES_DB: 'doko'
