version: '2'
services:
  webapp-dev:
    build: .
    command: bash -c "./docker-wait-for-postgres.sh db-dev && head -c 24 /dev/urandom > cookie_secret && python webapp.py"
    volumes:
      - ./:/dokomo
    depends_on:
      - db-dev
    ports:
      - "8888:8888"
    environment:
      DB_DEV_PORT_5432_TCP_ADDR: 'db-dev'
  db-dev:
    image: "mdillon/postgis:9.4"
    environment:
      POSTGRES_DB: 'doko'
